window.lessonMarkdown = `
# Unit 1 I Become a Student <br>by Lincoln Steffens

1 It is possible to get an education at a university. It has been done; not often, but the fact that a proportion, however small, of college students do get a start in interested, methodical study, proves my thesis, and the following personal experience I have to offer illustrates it and shows how to get around the faculty, the other students, and the whole college system of mind-fixing. My method might lose a boy his <abbr title="学位：大学颁发的学术证书">degree</abbr>, but a degree is not worth so much as the capacity and the drive to learn.

2 My method was hit on by accident and some instinct. I specialized. With several courses prescribed, I concentrated on the one or two that interested me most and worked intensively on my favorites. In my first two years, for example, I worked at English and political economy and read philosophy. At the beginning of my junior year I had several cinches in history. Now I liked history; I had neglected it partly because I rebelled at the way it was taught, as positive knowledge unrelated to politics, art, life, or anything else. The professors gave us chapters out of a few books to read and be quizzed on. Blessed as I was with a "bad memory," I could not commit to it anything that I did not understand and intellectually need. The bare record of the story of man, with names, dates, and irrelative events, bored me. But I had discovered in my readings of literature, philosophy, and political economy that history had light to throw upon unhistorical questions. So I proposed in my junior and senior years to specialize in history, taking all the courses required and those also that I had failed. With this in mind I listened attentively to the first introductory talk of Professor [William Cary Jones](https://en.wikipedia.org/wiki/William_Cary_Jones) on American constitutional history. He was a dull lecturer, but I noticed that, after telling us what pages of what books we must be prepared in, he listed off some other references "for those that may care to dig deeper."

3 When the rest of the class rushed out into the sunshine, I went up to the professor and, to his surprise, asked for this memorandum. He gave it to me. Up in the library I ran through the required chapters in the two different books, and they differed on several points. Turning to the other authorities, I saw that they disagreed on the same facts and also on others. The librarian, appealed to, helped me search the bookshelves till the library closed, and then I called on Professor Jones for more references. He was astonished, invited me in, and began to approve my industry, which astonished me. I was not trying to be a good boy; I was better than that: I was a curious boy. He lent me a couple of his books, and I went off to my club to read them. They only deepened the mystery, clearing up the historical question, but leaving the answer to be dug for and written.

4 The historians did not know! History was not a science, but a field for research, a field for me, for any young man, to explore, to make discoveries in and write a scientific report about. I was fascinated. As I went on from chapter to chapter, day after day, finding frequently essential differences of opinion and of fact, I saw more and more work to do. In this course, American constitutional history, I hunted far enough to suspect that the Fathers of the Republic who wrote our sacred Constitution of the United States not only did not, but did not want to, establish a democratic government, and I dreamed for a while—as I used as a child to play I was Napoleon or a trapper—I promised myself to write a true history of the making of the American Constitution. I did not do it; that chapter has been done or well begun since by two men: Smith of the University of Washington and <abbr title="查尔斯·比尔德 (Charles A. Beard)，美国著名历史学家">Beard</abbr> of Columbia. I found other events, men, and eras waiting for students. In all my other courses, in ancient, in European, and in modern history, the disagreeing authorities carried me back to the need of a fresh search for the original documents or other clinching evidence. Of course I did well in my classes. The history professors soon knew me as a student and seldom put a question to me except when the class didn't know the answer. Then Professor Jones would say, "Well, Steffens, tell them about it."

5 Fine. But vanity wasn't my ruling passion then. What I had was a quickening sense that I was learning a method of studying history and that every chapter of it, from the beginning of the world to the end, is crying out to be rewritten. There was something for Youth to do.

`;
